package com.santhosh.agentic_engineering_system.orchestration.domain;

public enum DecisionType {
    WORKFLOW_CREATED,
    WORKFLOW_STARTED,
    CLARIFICATION_REQUIRED,
    CLARIFICATION_PROVIDED,
    PLAN_GENERATED,
    POLICY_EVALUATED,
    PATCH_APPLIED,
    VALIDATION_STARTED,
    VALIDATION_SUCCEEDED,
    VALIDATION_FAILED,
    REPAIR_REQUESTED,
    ROLLBACK_PERFORMED,
    TASK_STARTED,
    TASK_SUCCEEDED,
    TASK_RETRY_SCHEDULED,
    TASK_FAILED,
    APPROVAL_REQUIRED,
    APPROVAL_GRANTED,
    WORKFLOW_COMPLETED,
    WORKFLOW_FAILED,
    SAFE_STOPPED
}
